spring:
  application:
    name: sparta-payment-system

  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
#
  sql:
    init:
      mode: always  # data.sql 자동 실행

#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/
#    suffix: .html

server:
  port: 8080

# JWT 설정
jwt:
  secret: "h61HwLrWre0+1jRCk6AU8vMx/0p2Okkxg+moMo1rSAM="
  expiration: 3600000  # 1시간 (ms)
